from Crypto.Cipher import DES
import os

def send_encrypted(channel, message):
    '''
    encrypt the message after creating a cipher and send it over the channel
    '''
    key = os.urandom(8) # Generate a random 8-byte key
    cipher = DES.new(key, DES.MODE_EAX) # Create a new cipher with the key and EAX mode
    nonce = cipher.nonce # Get the nonce generated by the cipher
    ciphertext, tag = cipher.encrypt_and_digest(message.encode()) # Encrypt and generate tag for the message

    # Send the encrypted message, tag and nonce over the channel
    channel.send(key)
    channel.send(tag)
    channel.send(nonce)
    channel.send(ciphertext)